# Generated by Django 2.0.7 on 2018-07-11 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_final', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='sala',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salas.Sala'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='turnos',
            field=models.ManyToManyField(to='salas.Turno'),
        ),
    ]
