# Generated by Django 2.0.7 on 2018-07-12 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0002_auto_20180711_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='hora_final',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
