# Generated by Django 2.0.7 on 2018-07-12 03:07

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0003_auto_20180711_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='hora_final',
        ),
        migrations.AddField(
            model_name='reserva',
            name='tiempo',
            field=models.CharField(choices=[('1', '1:00'), ('1.50', '1:30'), ('2', '2:00')], default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='dia',
            field=models.DateField(default=datetime.datetime(2018, 7, 12, 0, 7, 16, 508401)),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=datetime.datetime(2018, 7, 12, 0, 7, 16, 508401), null=True),
        ),
    ]
