# Generated by Django 2.0.7 on 2018-07-12 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0004_auto_20180712_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='hora_inicio',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='tiempo',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='hora_final',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='dia',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
