# Generated by Django 2.0.7 on 2018-07-13 00:05

from django.db import migrations, models
import django.db.models.deletion
import salas.models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0005_auto_20180712_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='hora_inicio',
            field=models.ForeignKey(null=salas.models.Horarios, on_delete=django.db.models.deletion.SET_NULL, to='salas.Turno'),
        ),
    ]
