# Generated by Django 2.0.7 on 2018-07-13 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0006_reserva_hora_inicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('LUNES', '0'), ('MARTES', '1'), ('MIERCOLES', '2'), ('JUEVES', '3'), ('VIERNES', '4'), ('SABADO', '5'), ('DOMINGO', '6')], max_length=1)),
                ('hora_inicio', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='hora_inicio',
        ),
        migrations.DeleteModel(
            name='Turno',
        ),
    ]
