# Generated by Django 2.0.7 on 2018-07-14 01:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0007_auto_20180712_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horarios',
            name='hora_inicio',
        ),
        migrations.AddField(
            model_name='horarios',
            name='horarios',
            field=models.CharField(choices=[('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('13:30', '13:30'), ('14:00', '14:00'), ('14:30', '14:30')], default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='horarios',
            name='dia',
            field=models.CharField(choices=[('0', 'LUNES'), ('1', 'MARTES'), ('2', 'MIERCOLES'), ('3', 'JUEVES'), ('4', 'VIERNES'), ('5', 'SABADO'), ('6', 'DOMINGO')], max_length=1),
        ),
    ]
