# Generated by Django 2.0.7 on 2018-07-14 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0008_auto_20180713_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='dia',
            field=models.DateField(),
        ),
    ]
