# Generated by Django 2.0.7 on 2018-10-31 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0010_reserva_horarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='dia',
            new_name='reservation_date',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='horarios',
        ),
        migrations.AddField(
            model_name='reserva',
            name='hora_fin',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='hora_inicio',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='usuario',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='sala',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sala',
            name='descripcion',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
